[task]
# tasks that can be run to bookstrap the project
install = {cmd = ["pixi", "install"]}
hooks = {
    cmd = ["pixi", "run", "pre-commit", "install"],
    depends-on = ["install"]
}
test = {
    cmd = ["pixi", "run", "pytest", "tests/"],
    depends-on = ["install"]
}
